[project]
name = "amuse-nbody6xx"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["nbody6xx/**/*.py"]
exclude = [
    "nbody6xx/packages",
    "nbody6xx/support",
    "nbody6xx/src",
    "nbody6xx/tests",
    "nbody6xx/debug.py"
    ]
artifacts = ["nbody6xx/nbody6xx_worker"]

[tool.hatch.build.targets.wheel.sources]
"nbody6xx" = "amuse/community/nbody6xx"

[tool.pytest.ini_options]
pythonpath = ["nbody6xx/tests/", "../../../../../tests"]

testpaths = ["nbody6xx/tests"]

