[project]
name = "amuse-ph4"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_ph4/**/*.py"]
exclude = [
    "amuse_ph4/packages",
    "amuse_ph4/support",
    "amuse_ph4/src",
    "amuse_ph4/tests",
    "amuse_ph4/test_scripts",
    "amuse_ph4/util"
    ]
artifacts = ["amuse_ph4/ph4_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_ph4/tests/", "../../../tests"]

testpaths = ["amuse_ph4/tests"]

# Test the installed package, and only CPU tests.
addopts = "--import-mode=append -k 'not gpu'"

