#!/bin/sh

export SGE_ROOT=/usr/local/Cluster-Apps/sge

NR_NODES=$1
shift
NR_PROCS=$1
shift
JAVA=$1
shift
ARGS=$*

RUNTIME=1:00:00

if [ `expr $NR_NODES \* 4` = "$NR_PROCS" ]; then

	OPTION=-4

elif [ `expr $NR_NODES \* 2` = "$NR_PROCS" ]; then

	OPTION=-2

fi

echo /usr/local/VU/reserve.sge/bin/prun -v -1 -asocial -t $RUNTIME -np $NR_NODES $JAVA $ARGS
exec /usr/local/VU/reserve.sge/bin/prun -v -1 -asocial -t $RUNTIME -np $NR_NODES $JAVA $ARGS

