.PHONY: clean
clean: clean_features

.PHONY: distclean
distclean: clean clean_comm_deps

.PHONY: clean_features
clean_features:
	rm -f configuration.sh config.status config.log
	rm -rf autom4te.cache

