#!/bin/env python

import urllib
import sys

def send_revision_to_server(revision):
    parameters = urllib.urlencode({'rev': revision})
    port = 9075
    f = urllib.urlopen("http://biesbosch.strw.leidenuniv.nl:{0}/check_svn_commit?{1}".format(port, parameters))
    try:
        return f.read()
    finally:
        f.close()

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print "Usage: {0} REPOS REV".format(argv[0])
        sys.exit(1)
        
    repository = sys.argv[1]
    revision = sys.argv[2]
    
    print send_revision_to_server(revision)
    
    
    
