/*******************************************************************************
* This is an ETICS parameter file used when the BOOST library is not available.
* When changing a parameter, the code has to be recompiled; if using BOOST, this
* is not required. The syntax is C++, just fill in the variables used in the
* regular initialization file. No error messages will be shown if input is bad.
*******************************************************************************/

Filename = "_nofile_ 0";
N        = 1000000;
Tcrit    = 16;
StepSize = 0.001953125;
dT1      = 0.001953125;
dT2      = 0.1;
Prefix   = "test_del_me";
Format   = "ascii";
