[project]
name = "amuse-secularmultiple"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.versioningit.vcs]
method = { module = "version_helper", value = "get_amuse_version", module-dir = "amuse_secularmultiple/support/shared" }

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_secularmultiple/**/*.py"]
exclude = [
    "amuse_secularmultiple/packages",
    "amuse_secularmultiple/support",
    "amuse_secularmultiple/src",
    "amuse_secularmultiple/tests"
    ]
artifacts = ["amuse_secularmultiple/secularmultiple_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_secularmultiple/tests/"]

testpaths = ["amuse_secularmultiple/tests"]

addopts = "--import-mode=append"    # test the installed package

