[project]
name = "amuse-phigrape-sapporo"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework",
    "amuse-phigrape"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["phigrape"]
exclude = ["phigrape/*"]
artifacts = ["phigrape/phigrape_sapporo_worker"]

[tool.hatch.build.targets.wheel.sources]
"phigrape" = "amuse/community/phigrape"

[tool.pytest.ini_options]
pythonpath = ["phigrape/tests/", "../../../../../tests"]

testpaths = ["phigrape/tests"]

