[project]
name = "amuse-athena"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["athena/**/*.py"]
exclude = [
    "athena/packages",
    "athena/support",
    "athena/src",
    "athena/tests"
    ]
artifacts = [
    "athena/athena_normal_worker",
    "athena/athena_selfgrav_worker",
    "athena/athena_mhd_worker",
    "athena/athena_scalar_worker",
    ]

[tool.hatch.build.targets.wheel.sources]
"athena" = "amuse/community/athena"

[tool.pytest.ini_options]
pythonpath = ["athena/tests/", "../../../../../tests"]

testpaths = ["athena/tests"]

