[build-system]
requires = [ "setuptools>=45.0.0", "setuptools_scm", "pip>=19.0.0", "wheel", "docutils>=0.6", "numpy>=1.2.2", "pytest>=5", "h5py>=1.1.0" ]

[tool.setuptools_scm]
write_to = "src/amuse/version.py"

[flake8]
max-line-length = 88

[tool.black]
line-length = 88
target-version = ["py37"]
