[project]
name = "amuse-fastkick"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_fastkick/**/*.py"]
exclude = [
    "amuse_fastkick/packages",
    "amuse_fastkick/support",
    "amuse_fastkick/src",
    "amuse_fastkick/tests"
    ]
artifacts = ["amuse_fastkick/fastkick_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_fastkick/tests/"]

testpaths = ["amuse_fastkick/tests"]

# Test the installed package, and only CPU tests
addopts = "--import-mode=append -k 'not TestFastKickGPU'"

