[project]
name = "amuse-seba"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["seba/**/*.py"]
exclude = [
    "seba/packages",
    "seba/support",
    "seba/src",
    "seba/tests"
    ]
artifacts = ["seba/seba_worker"]

[tool.hatch.build.targets.wheel.sources]
"seba" = "amuse/community/seba"

[tool.pytest.ini_options]
pythonpath = ["seba/tests/", "../../../../../tests"]

testpaths = ["seba/tests"]

