[project]
name = "amuse-capreole"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_capreole/**/*.py"]
exclude = [
    "amuse_capreole/packages",
    "amuse_capreole/support",
    "amuse_capreole/src",
    "amuse_capreole/tests"
    ]
artifacts = ["amuse_capreole/capreole_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_capreole/tests/"]

testpaths = ["amuse_capreole/tests"]

# Test the installed package.
#
# Disable test26 because it requires more resources than are available on the CI and
# on some ordinary machines and MPI settings, causing it to fail.
addopts = "--import-mode=append -k 'not test26'"

