[project]
name = "amuse-mi6-sapporo2"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework",
    "amuse-mi6"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_mi6"]
exclude = ["amuse_mi6/*"]
artifacts = ["amuse_mi6/mi6_sapporo2_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_mi6/tests/"]

testpaths = ["amuse_mi6/tests"]

addopts = "--import-mode=append"    # test the installed package

