set(TWIN_SRC_FILES
   code/accretion_abundances.f90
   code/atomic_data.f90
   code/begin.f90
   code/binary_history.f90
   code/constants.f90
   code/control.f90
   code/current_model_properties.f90
   code/diffusion.f90
   code/diffusion_coefficients.f90
   code/eostate.f90
   code/eostate_cache.f90
   code/eostate_types.f90
   code/extra_elements.f90
   code/extra_solver.f90
   code/extrapolate_dh.f90
   code/fcompare.f90
   code/fgb2hb.f90
   code/fgb2hb_comp.f90
   code/file_exists.f90
   code/filenames.f90
   code/funcs1_interface.f90
   code/initdat.f90
   code/initrun.f90
   code/interpolate.f90
   code/ionisation.f90
   code/load_star_model.f90
   code/lt2ubv.f90
   code/massloss.f90
   code/menc.f90
   code/mesh.f90
   code/ms2bss.f90
   code/neutrinos.f90
   code/nremesh.f90
   code/nucleosynthesis.f90
   code/opacity.f90
   code/opacity_co.f90
   code/output_input_model.f90
   code/output_properties.f90
   code/plotvariables.f90
   code/positron_fdirac.f90
   code/pruner.f90
   code/print_status.f90
   code/radiative_acceleration.f90
   code/reaction_rate_data.f90
   code/real_kind.f90
   code/remesh.f90
   code/semi_implicit.f90
   code/settings.f90
   code/solver.f90
   code/stars_structure.f90
   code/starting_values.f90
   code/structure_variables.f90
   code/step.f90
   code/test_variables.f90
   code/update.f90
   )

set(TWIN_LIBRARY_FILES
   code/export.f90
   code/import.f90
   code/library_v2.f90
   code/prtoft.f90
   )

