[project]
name = "amuse-{code}"
version = "0.0.1"
# use the line below instead of the version above if this code is inside the AMUSE
# repository
# dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework{framework_version}"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{{next_version}}.dev{{distance}}+{{vcs}}{{rev}}"
dirty = "{{base_version}}+d{{build_date:%Y%m%d}}"
distance-dirty = "{{next_version}}.dev{{distance}}+{{vcs}}{{rev}}.d{{build_date:%Y%m%d}}"

[tool.versioningit.vcs]
method = { module = "version_helper", value = "get_amuse_version", module-dir = "amuse_{code}/support/shared" }

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_{code}/**/*.py"]
exclude = [
    "amuse_{code}/packages",
    "amuse_{code}/support",
    "amuse_{code}/src",
    "amuse_{code}/tests"
    ]
artifacts = ["amuse_{code}/{code}_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_{code}/tests/"]

testpaths = ["amuse_{code}/tests"]

