[project]
name = "amuse-{code}-PACKAGE"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework{framework_version}",
    "amuse-{code}"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{{next_version}}.dev{{distance}}+{{vcs}}{{rev}}"
dirty = "{{base_version}}+d{{build_date:%Y%m%d}}"
distance-dirty = "{{next_version}}.dev{{distance}}+{{vcs}}{{rev}}.d{{build_date:%Y%m%d}}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["{code}"]
exclude = ["{code}/*"]
artifacts = ["{code}/{code}_PACKAGE_worker"]

[tool.hatch.build.targets.wheel.sources]
"{code}" = "amuse/community/{code}"

[tool.pytest.ini_options]
pythonpath = ["{code}/tests/", "../../../../../tests"]

testpaths = ["{code}/tests"]

