[project]
name = "amuse-sakura"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["sakura/**/*.py"]
exclude = [
    "sakura/packages",
    "sakura/support",
    "sakura/src",
    "sakura/tests"
    ]
artifacts = ["sakura/sakura_worker"]

[tool.hatch.build.targets.wheel.sources]
"sakura" = "amuse/community/sakura"

[tool.pytest.ini_options]
pythonpath = ["sakura/tests/", "../../../../../tests"]

testpaths = ["sakura/tests"]

