[project]
name = "amuse-kepler"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_kepler/**/*.py"]
exclude = [
    "amuse_kepler/packages",
    "amuse_kepler/support",
    "amuse_kepler/src",
    "amuse_kepler/tests"
    ]
artifacts = ["amuse_kepler/kepler_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_kepler/tests/", "../../../tests"]

testpaths = ["amuse_kepler/tests"]

