[project]
name = "amuse-gadget2"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["gadget2/**/*.py"]
exclude = [
    "gadget2/packages",
    "gadget2/support",
    "gadget2/src",
    "gadget2/tests"
    ]
artifacts = ["gadget2/gadget2_*_worker"]

[tool.hatch.build.targets.wheel.sources]
"gadget2" = "amuse/community/gadget2"

[tool.pytest.ini_options]
pythonpath = ["gadget2/tests/", "../../../../../tests"]

testpaths = ["gadget2/tests"]

