[project]
name = "amuse-mpiamrvac"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = [
    "mpiamrvac/**/*.py", "mpiamrvac/data"]
exclude = [
    "mpiamrvac/packages",
    "mpiamrvac/support",
    "mpiamrvac/src",
    "mpiamrvac/tests"
    ]
artifacts = [
    "mpiamrvac/mpiamrvac_3d_worker", "mpiamrvac/mpiamrvac_3dacc_worker",
    "mpiamrvac/mpiamrvac_2d_worker", "mpiamrvac/mpiamrvac_2dacc_worker",
    "mpiamrvac/mpiamrvac_1d_worker", "mpiamrvac/mpiamrvac_1dacc_worker",
    ]

[tool.hatch.build.targets.wheel.sources]
"mpiamrvac" = "amuse/community/mpiamrvac"

[tool.pytest.ini_options]
pythonpath = ["mpiamrvac/tests/", "../../../../../tests"]

testpaths = ["mpiamrvac/tests"]

