[project]
name = "amuse-mobse"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["mobse/**/*.py"]
exclude = [
    "mobse/packages",
    "mobse/support",
    "mobse/src",
    "mobse/tests"
    ]
artifacts = ["mobse/mobse_worker"]

[tool.hatch.build.targets.wheel.sources]
"mobse" = "amuse/community/mobse"

[tool.pytest.ini_options]
pythonpath = ["mobse/tests/", "../../../../../tests"]

testpaths = ["mobse/tests"]
