[project]
name = "amuse-huayno-opencl"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework",
    "amuse-huayno"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.versioningit.vcs]
method = { module = "version_helper", value = "get_amuse_version", module-dir = "amuse_huayno/support/shared" }

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_huayno"]
exclude = ["amuse_huayno/*"]
artifacts = ["amuse_huayno/huayno_opencl_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_huayno/tests/"]

testpaths = ["amuse_huayno/tests"]

# Test the installed package, and only OpenCL tests
addopts = "--import-mode=append -k opencl"

