#!/bin/bash

echo starting the AMUSE tutorial..

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export PYTHONHOME=${DIR}
export PATH=${PYTHONHOME}/bin:${PATH}
export PYTHONPATH=${PYTHONHOME}/customize
export PYTHON=${PYTHONHOME}/python

RUNDIR=/tmp/${USER}/amuse-tutorial

mkdir -p $RUNDIR

cp ${PYTHONHOME}/tutorial/* ${RUNDIR}/

exec python ${PYTHONHOME}/bin/ipython notebook --pylab inline --notebook-dir=${RUNDIR} --profile=nbserver


