[project]
name = "amuse-fi"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_fi/**/*.py", "amuse_fi/data"]
exclude = [
    "amuse_fi/packages",
    "amuse_fi/support",
    "amuse_fi/src",
    "amuse_fi/tests"
    ]
artifacts = [
    "amuse_fi/fi_worker",
    "amuse_fi/fi_map_worker",
    "amuse_fi/fi_map_mp_worker",
    "amuse_fi/fi_periodic_worker",
    "amuse_fi/fi_mp_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_fi/tests/", "../../../tests"]

testpaths = ["amuse_fi/tests"]
