[project]
name = "amuse-halogen"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["halogen/**/*.py"]
exclude = [
    "halogen/packages",
    "halogen/support",
    "halogen/src",
    "halogen/tests"
    ]
artifacts = ["halogen/halogen_worker"]

[tool.hatch.build.targets.wheel.sources]
"halogen" = "amuse/community/halogen"

[tool.pytest.ini_options]
pythonpath = ["halogen/tests/", "../../../../../tests"]

testpaths = ["halogen/tests"]

