[project]
name = "amuse-brutus"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["brutus/**/*.py"]
exclude = [
    "brutus/packages",
    "brutus/support",
    "brutus/src",
    "brutus/tests"
    ]
artifacts = ["brutus/brutus_worker"]

[tool.hatch.build.targets.wheel.sources]
"brutus" = "amuse/community/brutus"

[tool.pytest.ini_options]
pythonpath = ["brutus/tests/", "../../../../../tests"]

testpaths = ["brutus/tests"]

