#! /bin/csh -f
set EVOLDIR = Work/evol/code/twin/devel/
### set above to the directory (relative to your home) where the evolution 
### package is located.

if ( !($?evpath) ) set evpath = $HOME/$EVOLDIR
if ( !($?EV) ) set EV = $evpath/code/ev

set Z = $1

set name = zams$Z

if (-e $name.out1) rm -i $name.out1
if (-e $name.out2) rm -i $name.out2
if (-e $name.log) rm -i $name.log
if (-e $name.out) rm -i $name.out
if (-e $name.last1) rm -i $name.last1
if (-e $name.last2) rm -i $name.last2
if (-e $name.mod) rm -i $name.mod
if (-e $name.plt1) rm -i $name.plt1
if (-e $name.plt2) rm -i $name.plt2
if (-e $name.mdl1) rm -i $name.mdl1
if (-e $name.mdl2) rm -i $name.mdl2
# config files
echo 0 > fort.11
ln -s init.dat fort.22
ln -s init.run fort.23
# input files
ln -s $evpath/input/metals/z{$Z}/zams{$Z}_start.mod fort.14
ln -s $evpath/input/zams_start.out fort.18
ln -s $evpath/input/zams_start.mas fort.19
ln -s $evpath/input/metals/z{$Z}/phys.z{$Z} fort.20
ln -s $evpath/input/lt2ubv.dat fort.21

# output files
ln -s $name.out fort.1
ln -s $name.log fort.8
ln -s $name.mod fort.15
ln -s $name.mas fort.29
ln -s $name.plt1 fort.31
ln -s $name.mdl1 fort.33

# run code
#nice +19 $evpath/code/ev $name
$EV $name

# remove links
rm -f fort.16
rm -f fort.17
rm -f fort.18
rm -f fort.19
rm -f fort.20
rm -f fort.21
rm -f fort.22
rm -f fort.23

rm -f fort.1
rm -f fort.2
rm -f fort.3
rm -f fort.8
rm -f fort.9
rm -f fort.10
rm -f fort.11
rm -f fort.12
rm -f fort.13
rm -f fort.14
rm -f fort.15
rm -f fort.29
rm -f fort.31
rm -f fort.32
rm -f fort.33
rm -f fort.34

