[project]
name = "amuse-capreole"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["capreole/**/*.py"]
exclude = [
    "capreole/packages",
    "capreole/support",
    "capreole/src",
    "capreole/tests"
    ]
artifacts = ["capreole/capreole_worker"]

[tool.hatch.build.targets.wheel.sources]
"capreole" = "amuse/community/capreole"

[tool.pytest.ini_options]
pythonpath = ["capreole/tests/", "../../../../../tests"]

testpaths = ["capreole/tests"]

