[project]
name = "amuse-smalln"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["smalln/**/*.py"]
exclude = [
    "smalln/packages",
    "smalln/support",
    "smalln/src",
    "smalln/tests"
    ]
artifacts = ["smalln/smalln_worker"]

[tool.hatch.build.targets.wheel.sources]
"smalln" = "amuse/community/smalln"

[tool.pytest.ini_options]
pythonpath = ["smalln/tests/", "../../../../../tests"]

testpaths = ["smalln/tests"]

