[project]
name = "amuse-symple"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_symple/**/*.py"]
exclude = [
    "amuse_symple/packages",
    "amuse_symple/support",
    "amuse_symple/src",
    "amuse_symple/tests"
    ]
artifacts = ["amuse_symple/symple_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_symple/tests/"]

testpaths = ["amuse_symple/tests"]

# Test the installed package, and only files that are runnable by pytest
addopts = "--import-mode=append --ignore='symple/tests/test.py' --ignore='symple/tests/test_si.py'"

