[project]
name = "amuse-mocassin"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["mocassin/**/*.py"]
exclude = [
    "mocassin/packages",
    "mocassin/support",
    "mocassin/src",
    "mocassin/tests"
    ]
artifacts = [
    "mocassin/mocassin_worker",
    "mocassin/data"
    ]

[tool.hatch.build.targets.wheel.sources]
"mocassin" = "amuse/community/mocassin"

[tool.pytest.ini_options]
pythonpath = ["mocassin/tests/", "../../../../../tests"]

testpaths = ["mocassin/tests"]

