[project]
name = "amuse-krome"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["krome/**/*.py"]
exclude = [
    "krome/packages",
    "krome/support",
    "krome/src",
    "krome/tests"
    ]
artifacts = ["krome/krome_worker"]

[tool.hatch.build.targets.wheel.sources]
"krome" = "amuse/community/krome"

[tool.pytest.ini_options]
pythonpath = ["krome/tests/", "../../../../../tests"]

testpaths = ["krome/tests"]

