# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: inplace

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install gfortran libopenblas-dev libhdf5-openmpi-dev libgsl0-dev cmake libfftw3-3 libfftw3-dev libmpfr6 libmpfr-dev
        pip install numpy scipy matplotlib docutils mpi4py pytest pytest-timeout
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install amuse
      run: |
        pip install -e .
    - name: AMUSE code builds
      run: |
        python setup.py develop_build
    - name: check installation
      run: |
        amusifier --get-amuse-configmk
        pip list
    - name: archive build log
      uses: actions/upload-artifact@v1
      with:
          name: buildlog
          path: build.log
    - name: test core_tests
      run: |
        pytest --pyargs amuse.test.suite.core_tests -s
    - name: test compile_tests
      run: |
        ip link show
        echo $OMPI_MCA_btl_tcp_if_include
        pytest -k "not test29" --pyargs amuse.test.suite.compile_tests.test_c_implementation -sv
      env:
        OMPI_MCA_rmaps_base_oversubscribe: 1
        OMPI_MCA_btl_tcp_if_include: lo
    - name: test code_tests
      run: |
        pytest  --pyargs amuse.test.suite.codes_tests.test_bhtree -sv
        pytest  --pyargs amuse.test.suite.codes_tests.test_sse -sv
      env:
        OMPI_MCA_rmaps_base_oversubscribe: 1
        OMPI_MCA_btl_tcp_if_include: lo

